"""add marks to question table

Revision ID: 3f61216611ed
Revises: 553dedf19b79
Create Date: 2026-07-15 23:14:30.463353

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3f61216611ed'
down_revision: Union[str, None] = '553dedf19b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE questions "
        "ADD COLUMN marks DECIMAL(10, 2) NOT NULL DEFAULT 1.00 "
        "AFTER question"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'marks')
    # ### end Alembic commands ###
