"""add type column to questions table 

Revision ID: 3b0316d142dc
Revises: 3f61216611ed
Create Date: 2026-07-15 23:36:10.930785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0316d142dc'
down_revision: Union[str, None] = '3f61216611ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column(
            "is_global",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "is_global")
    # ### end Alembic commands ###
